name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 1 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - run: |
        python downloader.py
        date > LAST_UPDATED
    - run: |
        git config --global user.email you.siki@outlook.com
        git config --global user.name yousiki
        git add .
        git commit -m "updated by github actions" -a
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
  gitee:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: Yikun/hub-mirror-action@master
      with:
        src: github/yousiki
        dst: gitee/yousiki
        dst_key: ${{ secrets.GITEE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        white_list: "AdguardRules"
        force_update: true
  bitbucket:
    runs-on: ubuntu-latest
    steps:
    - uses: wearerequired/git-mirror-action@v1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.BITBUCKET_KEY }}
      with:
        source-repo: 'git@github.com:YOUSIKI/AdguardRules.git'
        destination-repo: 'git@bitbucket.org:YouSiki/adguardrules.git'
