name: AutoUpdate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '*/15 * * * *'
    
jobs:
  download-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: clean folder
      run: |
        rm -rf rules
        mkdir  rules
    
    - name: Adguard Simplified Dns Filter
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt"
        file-name: "adguardsdnsfilter.txt"
        location: "./rules"
    
    - name: EasyList
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://easylist-downloads.adblockplus.org/easylist.txt"
        file-name: "easylist.txt"
        location: "./rules"
    
    - name: EasyList-China
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://easylist-downloads.adblockplus.org/easylistchina.txt"
        file-name: "easylistchina.txt"
        location: "./rules"
    
    - name: EasyList-Cookie
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://easylist-downloads.adblockplus.org/easylist-cookie.txt"
        file-name: "easylist-cookie.txt"
        location: "./rules"
    
    - name: EasyPrivacy
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://easylist-downloads.adblockplus.org/easyprivacy.txt"
        file-name: "easyprivacy.txt"
        location: "./rules"
      
    - name: Anti-AD
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt"
        file-name: "anti-ad-easylist.txt"
        location: "./rules"
    
    - name: ChinaList 2.0
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/hopol/ChinaList2.0/master/ChinaList2.0.txt"
        file-name: "chinalist.txt"
        location: "./rules"
    
    - name: AdByBy-Lazy
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/adbyby/xwhyc-rules/master/lazy.txt"
        file-name: "adbyby-lazy.txt"
        location: "./rules"
    
    - name: AdByBy-Video
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/adbyby/xwhyc-rules/master/video.txt"
        file-name: "adbyby-video.txt"
        location: "./rules"
    
    - name: CJX-Annoyance
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt"
        file-name: "cjx-annoyance.txt"
        location: "./rules"
    
    - name: i-dont-care-about-cookies
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://www.i-dont-care-about-cookies.eu/abp/"
        file-name: "i-dont-care-about-cookies.txt"
        location: "./rules"
    
    - name: xinggsf-rule
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://gitee.com/xinggsf/Adblock-Rule/raw/master/rule.txt"
        file-name: "xinggsf-rule.txt"
        location: "./rules"
    
    - name: xinggsf-mv
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://gitee.com/xinggsf/Adblock-Rule/raw/master/mv.txt"
        file-name: "xinggsf-mv.txt"
        location: "./rules"
    
    - name: Zhihu
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/zsakvo/AdGuard-Custom-Rule/master/rule/zhihu.txt"
        file-name: "zhihu.txt"
        location: "./rules"
    
    - name: Zhihu Strict
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/zsakvo/AdGuard-Custom-Rule/master/rule/zhihu-strict.txt"
        file-name: "zhihu-strict.txt"
        location: "./rules"
    
    - name: Bilibili
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/Kr328/AdGuard-Custom-Rule/master/rule/bilibili.txt"
        file-name: "bilibili.txt"
        location: "./rules"
    
    - name: Spam404
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt"
        file-name: "spam404.txt"
        location: "./rules"
    
    - name: Nocoin
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt"
        file-name: "nocoin.txt"
        location: "./rules"
        
    - name: Urlhaus Filter Online
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/curbengh/urlhaus-filter/master/urlhaus-filter-online.txt"
        file-name: "urlhaus-filter-online.txt"
        location: "./rules"
        
    - name: Google Hosts
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/googlehosts/hosts/master/hosts-files/hosts"
        file-name: "google-hosts"
        location: "./rules"
    
    - name: Nocoin Hosts
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt"
        file-name: "nocoin-hosts"
        location: "./rules"
      
    - name: Urlhaus Filter Hosts
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/curbengh/urlhaus-filter/master/urlhaus-filter-hosts.txt"
        file-name: "urlhaus-filter-hosts"
        location: "./rules"
      
    - name: AdAway Hosts
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://adaway.org/hosts.txt"
        file-name: "adaway-hosts"
        location: "./rules"
    
    - name: AdWars Hosts
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts"
        file-name: "ad-wars-hosts"
        location: "./rules"
    
    - name: 1024 Hosts
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts"
        file-name: "1024-hosts"
        location: "./rules"
    
    - name: hblock Hosts
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://hblock.molinero.xyz/hosts"
        file-name: "hblock-hosts"
        location: "./rules"
    
    - name: mvps Hosts
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "http://winhelp2002.mvps.org/hosts.txt"
        file-name: "mvps-hosts"
        location: "./rules"
    
    - name: neo Hosts
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://hosts.nfz.moe/full/hosts"
        file-name: "neo-hosts"
        location: "./rules"
    
    - name: yhosts
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/vokins/yhosts/master/hosts"
        file-name: "yhosts-hosts"
        location: "./rules"
    
    - name: yourlist Hosts
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/yous/YousList/master/hosts.txt"
        file-name: "yourlist-hosts"
        location: "./rules"
    
    - name: steven black Hosts
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
        file-name: "steven-black-hosts"
        location: "./rules"
    
    - name: commit
      run: |
        if [ -z "$(git status --porcelain)" ]; then 
            exit 0
          else 
            git add .
            git config --local user.email "you.siki@outlook.com"
            git config --local user.name "yousiki"
            git commit -a -m "Github Actions @ $(date)"
          fi
    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}

  sync-to-gitee:
    runs-on: ubuntu-latest
    needs: download-and-update
    steps:
    - uses: actions/checkout@v2
    - uses: Yikun/hub-mirror-action@master
      with:
        src: github/yousiki
        dst: gitee/yousiki
        dst_key: ${{ secrets.GITEE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        white_list: "AdguardRules"
        force_update: true

  sync-to-bitbucket:
    runs-on: ubuntu-latest
    needs: download-and-update
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --unshallow origin
    - uses: spyoungtech/mirror-action@master
      with:
        REMOTE: 'https://YouSiki@bitbucket.org/YouSiki/adguardrules.git'
        GIT_PUSH_ARGS: '--force'
        GIT_USERNAME: yousiki
        GIT_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}
