name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 1 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - run: |
        python downloader.py
        date > LAST_UPDATED
    - run: |
        git config --global user.email you.siki@outlook.com
        git config --global user.name yousiki
        git add .
        git commit -m "updated by github actions" -a
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
    - run: |
        git add .
        git commit -m "sync" --allow-empty
        git push -f "https://yousiki:${{ secrets.GITEE_PASSWORD }}@gitee.com/yousiki/AdguardRules.git"
    - run: |
        git add .
        git commit -m "sync" --allow-empty
        git push -f "https://yousiki:${{ secrets.BITBUCKET_PASSWORD }}@bitbucket.org/YouSiki/adguardrules.git"
#     - uses: Yikun/hub-mirror-action@master
#       with:
#         src: github/yousiki
#         dst: gitee/yousiki
#         dst_key: ${{ secrets.GITEE_KEY }}
#         dst_token: ${{ secrets.GITEE_TOKEN }}
#         white_list: "AdguardRules"
#         force_update: true
